name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please searched for historical issues and check official documentation before opening this issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: Operation System
      description: Which operation system are you using?
      placeholder: ex. Windows11 23H2
    validations:
      required: true
  - type: input
    id: VOK
    attributes:
      label: VOK Version
      description: Which version of VOK are you using? Please ensure that you are using the latest version!
      placeholder: ex. v0.1.8
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce?
      description: A clear and concise description of what the bug is.
      placeholder: Steps to reproduce the behavior (you can use a gif to demonstrate the problem :)
    validations:
      required: true
  - type: input
    id: video-url
    attributes:
      label: Video URL
      description: The video URL for reproducing the issue (if applicable)
      placeholder: ex. https://www.youtube.com/watch?v=...

